security:
  providers:
    - jwt:
        atn-token:
          jwk.resource.uri: https://dev-06bzs1cu.us.auth0.com/.well-known/jwks.json
  web-server:
    defaults:
      authenticate: true
    paths:
      - path: "/hello"
        methods: ["get"]
